name: demo

on:
  push:
    branches:
      -master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: print node version
        run: |
          node -v
          npm -v
          echo 'hello'